import { z } from 'zod';

export const sourceConfidenceSchema = z.enum([
  'verified-official',
  'verified-description',
  'official-from-uploaded-gened-file',
  'needs-verification',
]).or(z.string());

export const courseSchema = z.object({
  id: z.string(),
  code: z.string().optional(),
  slug: z.string().optional(),
  courseId: z.string().optional(),
  nameTh: z.string().optional(),
  nameEn: z.string().optional(),
  titleTh: z.string().optional(),
  title: z.string().optional(),
  officialCategory: z.string().optional(),
  requirementGroup: z.string().optional(),
  credits: z.union([z.string(), z.number()]).nullable().optional(),
  category: z.string().optional(),
  subcategory: z.string().nullable().optional(),
  type: z.string().optional(),
  year: z.number().nullable().optional(),
  semester: z.union([z.string(), z.number()]).nullable().optional(),
  recommendedYear: z.number().optional(),
  recommendedSemester: z.union([z.string(), z.number()]).optional(),
  recommendedYearSemester: z.string().optional(),
  description: z.string().optional(),
  prerequisite: z.string().optional(),
  prerequisites: z.array(z.string()).optional(),
  prerequisiteOf: z.array(z.string()).optional(),
  officialPrerequisites: z.array(z.string()).optional(),
  officialPrerequisiteOf: z.array(z.string()).optional(),
  officialPrerequisiteText: z.string().optional(),
  legacyIds: z.array(z.string()).optional(),
  dangerousToFail: z.boolean().optional(),
  whyItMatters: z.string().optional(),
  seniorTips: z.array(z.string()).optional(),
  careerPaths: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  projectIdeas: z.array(z.string()).optional(),
  sourceConfidence: sourceConfidenceSchema.optional(),
  sourcePage: z.string().nullable().optional(),
  sourceRef: z.string().nullable().optional(),
  sourceNote: z.string().optional(),
  sourceFile: z.string().optional(),
  sourceSection: z.string().optional(),
  sourceStatus: z.string().optional(),
  needsVerification: z.boolean().optional(),
  isPlaceholder: z.boolean().optional(),
  isClickable: z.boolean().optional(),
  isGeneralEducation: z.boolean().optional(),
  isMajorCourse: z.boolean().optional(),
}).passthrough();

export type CourseData = z.infer<typeof courseSchema>;
